name: build-image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  fetch-installer-and-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: run fetchInstaller.ts
        run: deno run --allow-net --allow-write fetchInstaller.ts

      - name: check
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
