name: build-image

on:
  push:
    tags:
     - '*'

jobs:
  fetch-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: run fetchIstannler.ts
        run: deno run --allow-net --allow-write fetchInstaller.ts
